Vagrant.configure("2") do |config|
  config.vm.box = "bandit145/centos_stream9_arm"
  config.vm.network "private_network" , ip: "192.168.56.22"
  config.vm.network "public_network"
  config.vm.provision "shell", inline: <<-SHELL
   yum install httpd vim tmux wget unzip git net-tools -y
SHELL
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
  end
end