Vagrant.configure("2") do |config|
  config.vm.box = "bandit145/centos_stream9_arm"
  config.vm.network "private_network" , ip: "192.168.56.28"
  config.vm.network "public_network"
  config.vm.provision "shell", inline: <<-SHELL
   yum install httpd vim tmux wget unzip git net-tools -y
   systemctl start httpd
   systemctl enable httpd
   systemctl stop firewalld
   mkdir -p /temp/finance
   cd /tmp/finance
   wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
   unzip -o 2135_mini_finance.zip
   cp -r 2135_mini_finance/* /var/www/html/
   systemctl restart httpd
   cd /tmp/
   rm -rf /tmp/finance
SHELL
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
  end
end